plugins {
    id 'java'
    id 'io.qameta.allure' version "4.3.0"
}
def allureVersion = "2.34.0"

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation "io.qameta.allure:allure-junit5:$allureVersion"
    testImplementation "io.qameta.allure:allure-selenide:$allureVersion"
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.2")
    testImplementation("com.codeborne:selenide:7.17.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("net.datafaker:datafaker:2.7.0")
    testImplementation("org.aeonbits.owner:owner:1.0.12")
}

test {
    useJUnitPlatform()
    // Передаем все системные свойства из командной строки/IDE в тесты
    systemProperties = System.properties

    // ИЛИ конкретно одно свойство (если не хотите передавать все):
    // systemProperty "run", System.getProperty("run")
}
tasks.register('uiTest', Test) {
    group = 'verification'
    description = 'Запускает UI тесты (опционально с доп. тегом)'

    // ВАЖНО: Без этих строк будет NO-SOURCE
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    outputs.upToDateWhen { false }

    useJUnitPlatform {
        def tag = System.getProperty("tag")
        // если тэг указан - запускаем ui + тэг тест
        // если нет - только ui
        if (tag != null && !tag.isBlank()) {
            includeTags("UI & ${tag}")
        } else {
            includeTags("UI")
        }
    }
    systemProperties(System.getProperties())
}
tasks.register('apiTest', Test) {
    group = 'verification'
    description = 'Запускает API тесты (опционально с доп. тегом)'

    // ВАЖНО: Без этих строк будет NO-SOURCE
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    outputs.upToDateWhen { false }

    useJUnitPlatform {
        def tag = System.getProperty("tag")
        // если тэг указан - запускаем api + тэг тест
        // если нет - только api
        if (tag != null && !tag.isBlank()) {
            includeTags("API & ${tag}")
        } else {
            includeTags("API")
        }
    }
    systemProperties(System.getProperties())
}

tasks.register('positiveTest', Test) {
    group = 'verification'
    description = 'Запускает все позитивные тесты'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }//отключение проверки актуальности задачи(тесты кааждый раз запускаются)

    useJUnitPlatform {
        includeTags 'Positive'
    }
}

tasks.register('negativeTest', Test) {
    group = 'verification'
    description = 'Запускает все негативные тесты'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }//отключение проверки актуальности задачи(тесты кааждый раз запускаются)

    useJUnitPlatform {
        includeTags 'Negative'
    }
}
tasks.register('loginTest', Test) {
    group = 'verification'
    description = 'Запускает все тесты Login'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }//отключение проверки актуальности задачи(тесты кааждый раз запускаются)

    useJUnitPlatform {
        includeTags 'Login'
    }
}
tasks.register('cartTest', Test) {
    group = 'verification'
    description = 'Запускает все тесты Cart'

    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    outputs.upToDateWhen { false }//отключение проверки актуальности задачи(тесты кааждый раз запускаются)

    useJUnitPlatform {
        includeTags 'Cart'
    }
}
